# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_platform', '0003_auto_20171116_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommanager',
            name='public_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
