# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_platform', '0004_roommanager_public_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommanager',
            old_name='public_name',
            new_name='name',
        ),
    ]
