# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_platform', '0005_auto_20180216_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommanager',
            name='mobile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='roommanager',
            name='ussd',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
